### ISSUE TITLE
模型中offset的问题

### ISSUE THREAD

**Issue by AI-rcl** [Prayforhanluo/CTR_Algorithm#1]
大佬，请问一下模型中对输入加上一个offset 有什么作用呢，为啥offset还要向右偏移了一位呢？初次学习，还请大佬指教，感谢！

**Comment by Prayforhanluo** [comment]
> 大佬，请问一下模型中对输入加上一个offset 有什么作用呢，为啥offset还要向右偏移了一位呢？初次学习，还请大佬指教，感谢！

你可以看看example里面的例子，因为要做embedding， 这里输入的数据经过label encode后，每一列是单独的label_encode， 而embedding的时候为了一次性的过一层embedding layer，就需要累加编码，比如A特征为0,1两种，B特征为0,1,2三种，那么需要把B的0,1,2变成2,3,4。这样在embedding中  A的0 和B的0不会被混淆

**Comment by AI-rcl** [comment]
原来如此，感谢大佬指点
